<?php

namespace App\ArrayObjects;

use App\Entity\User;

/**
 * Class UserArray
 */
class UserArray extends \ArrayObject
***REMOVED***
    /**
     * Inherited method.
     *
     * @param mixed $index
     * @param mixed $newval
     * @return void
     */
    public function offsetSet($index, $newval)
    ***REMOVED***
        if ($index instanceof User)***REMOVED***
            parent::offsetSet($index, $newval); // TODO: Change the autogenerated stub
    ***REMOVED***
        throw new \InvalidArgumentException('Index ' . $index . ' not instance of ' . User::class);
***REMOVED***
***REMOVED***
