<?php

namespace App\ArrayObjects;

use App\Entity\User;

class UserArray extends \ArrayObject
***REMOVED***
    public function offsetSet($index, $newval)
    ***REMOVED***
        if ($index instanceof User)***REMOVED***
            parent::offsetSet($index, $newval); // TODO: Change the autogenerated stub
    ***REMOVED***
        throw new \InvalidArgumentException('Index ' . $index . ' not instance of ' . User::class);
***REMOVED***

***REMOVED***
