<?php

use Phinx\Migration\AbstractMigration;
use Phinx\Db\Adapter\MysqlAdapter;

class Init extends AbstractMigration
{
    public function change()
    {
        $this->execute("ALTER DATABASE CHARACTER SET 'utf8';");
        $this->execute("ALTER DATABASE COLLATE='utf8_general_ci';");
        $table = $this->table("article", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('article_title_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'hash']);
        $table->addColumn('article_description_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'article_title_id']);
        $table->addColumn('article_quality_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'article_description_id']);
        $table->addColumn('storage_place_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'article_quality_hash']);
        $table->addColumn('department_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'storage_place_hash']);
        $table->addColumn('date', 'datetime', ['null' => false, 'after' => 'department_hash']);
        $table->addColumn('quantity', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'date']);
        $table->addColumn('replacement', 'datetime', ['null' => true, 'after' => 'quantity']);
        $table->addColumn('barcode', 'string', ['null' => true, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'replacement']);
        $table->addColumn('available_for_rent', 'boolean', ['null' => false, 'default' => "0", 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3, 'after' => 'barcode']);
        $table->addColumn('rent_price', 'decimal', ['null' => true, 'precision' => 11, 'scale' => 2, 'after' => 'available_for_rent']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'rent_price']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("article");
        $table->removeIndexByName("fk_article_article_description1_idx");
        $table = $this->table("article");
        $table->addIndex(['article_description_id'], ['name' => "fk_article_article_description1_idx", 'unique' => false])->save();
        $table = $this->table("article");
        $table->removeIndexByName("fk_article_article_title1_idx");
        $table = $this->table("article");
        $table->addIndex(['article_title_id'], ['name' => "fk_article_article_title1_idx", 'unique' => false])->save();
        $table = $this->table("article");
        $table->removeIndexByName("fk_article_article_quality1_idx");
        $table = $this->table("article");
        $table->addIndex(['article_quality_hash'], ['name' => "fk_article_article_quality1_idx", 'unique' => false])->save();
        $table = $this->table("article");
        $table->removeIndexByName("fk_article_storage_place1_idx");
        $table = $this->table("article");
        $table->addIndex(['storage_place_hash'], ['name' => "fk_article_storage_place1_idx", 'unique' => false])->save();
        $table = $this->table("article_description", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('name_de', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name_en', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name_it']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('deleted_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('deleted_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'deleted_at']);
        $table->save();
        $table = $this->table("article_image", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('article_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('image_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'article_hash']);
        $table->save();
        $table = $this->table("article_image");
        $table->removeIndexByName("fk_article_has_image_image1_idx");
        $table = $this->table("article_image");
        $table->addIndex(['image_hash'], ['name' => "fk_article_has_image_image1_idx", 'unique' => false])->save();
        $table = $this->table("article_image");
        $table->removeIndexByName("fk_article_has_image_article1_idx");
        $table = $this->table("article_image");
        $table->addIndex(['article_hash'], ['name' => "fk_article_has_image_article1_idx", 'unique' => false])->save();
        $table = $this->table("article_quality", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('level', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'hash']);
        $table->addColumn('name_de', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'level']);
        $table->addColumn('name_en', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->save();
        $table = $this->table("article_title", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('name_de', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name_en', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name_it']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("city", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('country', 'string', ['null' => false, 'limit' => 2, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "Land", 'after' => 'id']);
        $table->addColumn('state', 'string', ['null' => false, 'limit' => 10, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'comment' => "Kanton / Bundesland / Region", 'after' => 'country']);
        $table->addColumn('number', 'string', ['null' => false, 'limit' => 10, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'state']);
        $table->addColumn('number2', 'string', ['null' => true, 'limit' => 10, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'number']);
        $table->addColumn('title_de', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'number2']);
        $table->addColumn('title_fr', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'title_de']);
        $table->addColumn('title_it', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'title_fr']);
        $table->addColumn('title_en', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_unicode_ci", 'encoding' => "utf8", 'after' => 'title_it']);
        $table->addColumn('created', 'datetime', ['null' => true, 'after' => 'title_en']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created']);
        $table->addColumn('modified', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified']);
        $table->addColumn('deleted', 'boolean', ['null' => false, 'default' => "0", 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3, 'after' => 'modified_by']);
        $table->addColumn('deleted_at', 'datetime', ['null' => true, 'after' => 'deleted']);
        $table->addColumn('deleted_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'deleted_at']);
        $table->save();
        $table = $this->table("city");
        $table->removeIndexByName("idx_country_number");
        $table = $this->table("city");
        $table->addIndex(['country','number'], ['name' => "idx_country_number", 'unique' => false])->save();
        $table = $this->table("department", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('department_group_hash', 'string', ['null' => false, 'limit' => 155, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('department_region_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'department_group_hash']);
        $table->addColumn('department_type_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'department_region_hash']);
        $table->addColumn('city_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'department_type_hash']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'city_id']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("department");
        $table->removeIndexByName("fk_department_department_group_idx");
        $table = $this->table("department");
        $table->addIndex(['department_region_hash'], ['name' => "fk_department_department_group_idx", 'unique' => false])->save();
        $table = $this->table("department");
        $table->removeIndexByName("fk_department_city1_idx");
        $table = $this->table("department");
        $table->addIndex(['city_id'], ['name' => "fk_department_city1_idx", 'unique' => false])->save();
        $table = $this->table("department");
        $table->removeIndexByName("fk_department_department_type1_idx");
        $table = $this->table("department");
        $table->addIndex(['department_type_hash'], ['name' => "fk_department_department_type1_idx", 'unique' => false])->save();
        $table = $this->table("department");
        $table->removeIndexByName("fk_department_department_group1_idx");
        $table = $this->table("department");
        $table->addIndex(['department_group_hash'], ['name' => "fk_department_department_group1_idx", 'unique' => false])->save();
        $table = $this->table("department_event", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('department_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('event_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'department_hash']);
        $table->addColumn('department_group_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'event_hash']);
        $table->save();
        $table = $this->table("department_event");
        $table->removeIndexByName("fk_department_has_event_event1_idx");
        $table = $this->table("department_event");
        $table->addIndex(['event_hash'], ['name' => "fk_department_has_event_event1_idx", 'unique' => false])->save();
        $table = $this->table("department_event");
        $table->removeIndexByName("fk_department_has_event_department1_idx");
        $table = $this->table("department_event");
        $table->addIndex(['department_hash'], ['name' => "fk_department_has_event_department1_idx", 'unique' => false])->save();
        $table = $this->table("department_event");
        $table->removeIndexByName("fk_department_event_department_group1_idx");
        $table = $this->table("department_event");
        $table->addIndex(['department_group_hash'], ['name' => "fk_department_event_department_group1_idx", 'unique' => false])->save();
        $table = $this->table("department_group", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "epart", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name_de', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('name_en', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->save();
        $table = $this->table("department_region", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name_de', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('name_en', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->save();
        $table = $this->table("department_type", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name_de', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('name_en', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name_it']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("educational_course", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('educational_course_title_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'hash']);
        $table->addColumn('educational_course_description_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'educational_course_title_id']);
        $table->addColumn('educational_course_organiser_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'educational_course_description_id']);
        $table->addColumn('department_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'comment' => "The organizer", 'after' => 'educational_course_organiser_hash']);
        $table->addColumn('city_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'comment' => "Where the edu_course is taking place", 'after' => 'department_hash']);
        $table->addColumn('position_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'comment' => "The minimum required position to participate", 'after' => 'city_id']);
        $table->addColumn('price', 'decimal', ['null' => false, 'precision' => 10, 'after' => 'position_hash']);
        $table->addColumn('start_date', 'datetime', ['null' => false, 'after' => 'price']);
        $table->addColumn('end_date', 'datetime', ['null' => false, 'after' => 'start_date']);
        $table->addColumn('minimum_age', 'year', ['null' => false, 'limit' => 4, 'after' => 'end_date']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'minimum_age']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("educational_course");
        $table->removeIndexByName("fk_education_course_educational_course_title1_idx");
        $table = $this->table("educational_course");
        $table->addIndex(['educational_course_title_id'], ['name' => "fk_education_course_educational_course_title1_idx", 'unique' => false])->save();
        $table = $this->table("educational_course");
        $table->removeIndexByName("fk_education_course_educational_course_description1_idx");
        $table = $this->table("educational_course");
        $table->addIndex(['educational_course_description_id'], ['name' => "fk_education_course_educational_course_description1_idx", 'unique' => false])->save();
        $table = $this->table("educational_course");
        $table->removeIndexByName("fk_education_course_department1_idx");
        $table = $this->table("educational_course");
        $table->addIndex(['department_hash'], ['name' => "fk_education_course_department1_idx", 'unique' => false])->save();
        $table = $this->table("educational_course");
        $table->removeIndexByName("fk_education_course_position1_idx");
        $table = $this->table("educational_course");
        $table->addIndex(['position_hash'], ['name' => "fk_education_course_position1_idx", 'unique' => false])->save();
        $table = $this->table("educational_course");
        $table->removeIndexByName("fk_education_course_city1_idx");
        $table = $this->table("educational_course");
        $table->addIndex(['city_id'], ['name' => "fk_education_course_city1_idx", 'unique' => false])->save();
        $table = $this->table("educational_course");
        $table->removeIndexByName("fk_education_course_educational_course_organiser1_idx");
        $table = $this->table("educational_course");
        $table->addIndex(['educational_course_organiser_hash'], ['name' => "fk_education_course_educational_course_organiser1_idx", 'unique' => false])->save();
        $table = $this->table("educational_course_description", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('name_de', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name_en', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name_it']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("educational_course_image", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('educational_course_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('image_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'educational_course_hash']);
        $table->save();
        $table = $this->table("educational_course_image");
        $table->removeIndexByName("fk_educational_course_has_image_image1_idx");
        $table = $this->table("educational_course_image");
        $table->addIndex(['image_hash'], ['name' => "fk_educational_course_has_image_image1_idx", 'unique' => false])->save();
        $table = $this->table("educational_course_image");
        $table->removeIndexByName("fk_educational_course_has_image_educational_course1_idx");
        $table = $this->table("educational_course_image");
        $table->addIndex(['educational_course_hash'], ['name' => "fk_educational_course_has_image_educational_course1_idx", 'unique' => false])->save();
        $table = $this->table("educational_course_organiser", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('user_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('name', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'user_hash']);
        $table->addColumn('phone', 'string', ['null' => true, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name']);
        $table->addColumn('email', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'phone']);
        $table->addColumn('notes', 'string', ['null' => true, 'limit' => 1500, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'email']);
        $table->addColumn('mobile', 'string', ['null' => true, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'notes']);
        $table->save();
        $table = $this->table("educational_course_organiser");
        $table->removeIndexByName("fk_educational_course_organiser_user1_idx");
        $table = $this->table("educational_course_organiser");
        $table->addIndex(['user_hash'], ['name' => "fk_educational_course_organiser_user1_idx", 'unique' => false])->save();
        $table = $this->table("educational_course_participant", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('educational_course_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('user_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'educational_course_hash']);
        $table->save();
        $table = $this->table("educational_course_participant");
        $table->removeIndexByName("fk_educational_course_has_user_user1_idx");
        $table = $this->table("educational_course_participant");
        $table->addIndex(['user_hash'], ['name' => "fk_educational_course_has_user_user1_idx", 'unique' => false])->save();
        $table = $this->table("educational_course_participant");
        $table->removeIndexByName("fk_educational_course_has_user_educational_course1_idx");
        $table = $this->table("educational_course_participant");
        $table->addIndex(['educational_course_hash'], ['name' => "fk_educational_course_has_user_educational_course1_idx", 'unique' => false])->save();
        $table = $this->table("educational_course_title", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('name_de', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'comment' => "Force the user to have a title of maximum 45 chars length!", 'after' => 'id']);
        $table->addColumn('name_en', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name_it']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("email_token", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('user_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('token', 'string', ['null' => false, 'limit' => 80, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'user_hash']);
        $table->addColumn('issued_at', 'datetime', ['null' => false, 'default' => "CURRENT_TIMESTAMP", 'after' => 'token']);
        $table->save();
        $table = $this->table("event", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('event_title_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'hash']);
        $table->addColumn('event_description_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'event_title_id']);
        $table->addColumn('price', 'decimal', ['null' => false, 'precision' => 10, 'after' => 'event_description_id']);
        $table->addColumn('start', 'datetime', ['null' => false, 'after' => 'price']);
        $table->addColumn('end', 'datetime', ['null' => false, 'after' => 'start']);
        $table->addColumn('start_leader', 'datetime', ['null' => false, 'after' => 'end']);
        $table->addColumn('end_leader', 'datetime', ['null' => false, 'after' => 'start_leader']);
        $table->addColumn('public', 'integer', ['null' => false, 'default' => "0", 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3, 'after' => 'end_leader']);
        $table->addColumn('publicize_at', 'datetime', ['null' => false, 'after' => 'public']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'publicize_at']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("event");
        $table->removeIndexByName("fk_event_event_description1_idx");
        $table = $this->table("event");
        $table->addIndex(['event_description_id'], ['name' => "fk_event_event_description1_idx", 'unique' => false])->save();
        $table = $this->table("event");
        $table->removeIndexByName("fk_event_event_title1_idx");
        $table = $this->table("event");
        $table->addIndex(['event_title_id'], ['name' => "fk_event_event_title1_idx", 'unique' => false])->save();
        $table = $this->table("event_article", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('article_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('event_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'article_hash']);
        $table->addColumn('accountable_user_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'event_hash']);
        $table->addColumn('quantity', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'accountable_user_hash']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'after' => 'quantity']);
        $table->addColumn('created_by', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archieved_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("event_article");
        $table->removeIndexByName("fk_article_has_event_event1_idx");
        $table = $this->table("event_article");
        $table->addIndex(['event_hash'], ['name' => "fk_article_has_event_event1_idx", 'unique' => false])->save();
        $table = $this->table("event_article");
        $table->removeIndexByName("fk_article_has_event_article1_idx");
        $table = $this->table("event_article");
        $table->addIndex(['article_hash'], ['name' => "fk_article_has_event_article1_idx", 'unique' => false])->save();
        $table = $this->table("event_article");
        $table->removeIndexByName("fk_event_article_app_user1_idx");
        $table = $this->table("event_article");
        $table->addIndex(['accountable_user_hash'], ['name' => "fk_event_article_app_user1_idx", 'unique' => false])->save();
        $table = $this->table("event_description", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('name_de', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name_en', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'text', ['null' => false, 'limit' => MysqlAdapter::TEXT_LONG, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name_it']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("event_image", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('image_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('event_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'image_hash']);
        $table->save();
        $table = $this->table("event_image");
        $table->removeIndexByName("fk_image_has_event_event1_idx");
        $table = $this->table("event_image");
        $table->addIndex(['event_hash'], ['name' => "fk_image_has_event_event1_idx", 'unique' => false])->save();
        $table = $this->table("event_image");
        $table->removeIndexByName("fk_image_has_event_image1_idx");
        $table = $this->table("event_image");
        $table->addIndex(['image_hash'], ['name' => "fk_image_has_event_image1_idx", 'unique' => false])->save();
        $table = $this->table("event_participant", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable', 'comment' => "This table is linked to event because a children can participate via any department to an event. it does not matter via which department it\\\\\\\\\'s participation is registered, bc the children is registered in a department."]);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('user_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'comment' => "This table is linked to event because a children can participate via any department to an event. it does not matter via which department it\\\\\\\\\'s participation is registered, bc the children is registered in a department.", 'after' => 'hash']);
        $table->addColumn('event_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'comment' => "This table is linked to event because a children can participate via any department to an event. it does not matter via which department it\\\\\\\\\'s participation is registered, bc the children is registered in a department.", 'after' => 'user_hash']);
        $table->addColumn('event_participation_status_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'event_hash']);
        $table->addColumn('message', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'event_participation_status_hash']);
        $table->addColumn('created_at', 'datetime', ['null' => false, 'after' => 'message']);
        $table->addColumn('created_by', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("event_participant");
        $table->removeIndexByName("fk_user_has_event_event1_idx");
        $table = $this->table("event_participant");
        $table->addIndex(['event_hash'], ['name' => "fk_user_has_event_event1_idx", 'unique' => false])->save();
        $table = $this->table("event_participant");
        $table->removeIndexByName("fk_user_has_event_user1_idx");
        $table = $this->table("event_participant");
        $table->addIndex(['user_hash'], ['name' => "fk_user_has_event_user1_idx", 'unique' => false])->save();
        $table = $this->table("event_participant");
        $table->removeIndexByName("fk_event_participant_event_participation_status1_idx");
        $table = $this->table("event_participant");
        $table->addIndex(['event_participation_status_hash'], ['name' => "fk_event_participant_event_participation_status1_idx", 'unique' => false])->save();
        $table = $this->table("event_participation_status", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name_de', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('name_en', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->save();
        $table = $this->table("event_title", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('name_de', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'comment' => "Force the user to have a title of maximum 45 chars length!", 'after' => 'id']);
        $table->addColumn('name_en', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name_it']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("gender", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name_de', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('name_en', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->save();
        $table = $this->table("image", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('url', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('type', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'url']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'type']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("language", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 5, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('abbreviation', 'string', ['null' => false, 'limit' => 2, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name']);
        $table->save();
        $table = $this->table("permission", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('level', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'hash']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'level']);
        $table->save();
        $table = $this->table("position", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name_de', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('name_en', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_de']);
        $table->addColumn('name_fr', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_en']);
        $table->addColumn('name_it', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'name_fr']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name_it']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("sl_chest", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("sl_corridor", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("sl_location", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("sl_room", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("sl_shelf", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("sl_tray", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("storage_place", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('department_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'hash']);
        $table->addColumn('sl_location_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'department_hash']);
        $table->addColumn('sl_room_hash', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'sl_location_hash']);
        $table->addColumn('sl_corridor_hash', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'sl_room_hash']);
        $table->addColumn('sl_shelf_hash', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'sl_corridor_hash']);
        $table->addColumn('sl_tray_hash', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'sl_shelf_hash']);
        $table->addColumn('sl_chest_hash', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'sl_tray_hash']);
        $table->addColumn('name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'sl_chest_hash']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'name']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("storage_place");
        $table->removeIndexByName("fk_storage_place_sl_location1_idx");
        $table = $this->table("storage_place");
        $table->addIndex(['sl_location_hash'], ['name' => "fk_storage_place_sl_location1_idx", 'unique' => false])->save();
        $table = $this->table("storage_place");
        $table->removeIndexByName("fk_storage_place_sl_room1_idx");
        $table = $this->table("storage_place");
        $table->addIndex(['sl_room_hash'], ['name' => "fk_storage_place_sl_room1_idx", 'unique' => false])->save();
        $table = $this->table("storage_place");
        $table->removeIndexByName("fk_storage_place_sl_corridor1_idx");
        $table = $this->table("storage_place");
        $table->addIndex(['sl_corridor_hash'], ['name' => "fk_storage_place_sl_corridor1_idx", 'unique' => false])->save();
        $table = $this->table("storage_place");
        $table->removeIndexByName("fk_storage_place_sl_shelf1_idx");
        $table = $this->table("storage_place");
        $table->addIndex(['sl_shelf_hash'], ['name' => "fk_storage_place_sl_shelf1_idx", 'unique' => false])->save();
        $table = $this->table("storage_place");
        $table->removeIndexByName("fk_storage_place_sl_tray1_idx");
        $table = $this->table("storage_place");
        $table->addIndex(['sl_tray_hash'], ['name' => "fk_storage_place_sl_tray1_idx", 'unique' => false])->save();
        $table = $this->table("storage_place");
        $table->removeIndexByName("fk_storage_place_sl_chest1_idx");
        $table = $this->table("storage_place");
        $table->addIndex(['sl_chest_hash'], ['name' => "fk_storage_place_sl_chest1_idx", 'unique' => false])->save();
        $table = $this->table("user", ['id' => false, 'primary_key' => ["id"], 'engine' => "InnoDB", 'encoding' => "utf8", 'collation' => "utf8_general_ci", 'comment' => "", 'row_format' => "Compact"]);
        $table->addColumn('id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'identity' => 'enable']);
        $table->addColumn('hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'id']);
        $table->addColumn('city_id', 'integer', ['null' => false, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'hash']);
        $table->addColumn('language_hash', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'city_id']);
        $table->addColumn('permission_hash', 'string', ['null' => false, 'default' => "4", 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'comment' => "See permission table", 'after' => 'language_hash']);
        $table->addColumn('department_hash', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'permission_hash']);
        $table->addColumn('position_hash', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'department_hash']);
        $table->addColumn('gender_hash', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'position_hash']);
        $table->addColumn('first_name', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'gender_hash']);
        $table->addColumn('email', 'string', ['null' => false, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'first_name']);
        $table->addColumn('username', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'email']);
        $table->addColumn('password', 'string', ['null' => false, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'username']);
        $table->addColumn('signup_completed', 'integer', ['null' => false, 'default' => "0", 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3, 'after' => 'password']);
        $table->addColumn('email_verified', 'boolean', ['null' => false, 'default' => "0", 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3, 'after' => 'signup_completed']);
        $table->addColumn('js_certificate', 'integer', ['null' => false, 'default' => "0", 'limit' => MysqlAdapter::INT_TINY, 'precision' => 3, 'after' => 'email_verified']);
        $table->addColumn('last_name', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'js_certificate']);
        $table->addColumn('address', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'last_name']);
        $table->addColumn('cevi_name', 'string', ['null' => true, 'limit' => 255, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'address']);
        $table->addColumn('birthdate', 'date', ['null' => true, 'after' => 'cevi_name']);
        $table->addColumn('phone', 'string', ['null' => true, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'birthdate']);
        $table->addColumn('mobile', 'string', ['null' => true, 'limit' => 45, 'collation' => "utf8_general_ci", 'encoding' => "utf8", 'after' => 'phone']);
        $table->addColumn('js_certificate_until', 'year', ['null' => true, 'limit' => 4, 'after' => 'mobile']);
        $table->addColumn('created_at', 'datetime', ['null' => true, 'after' => 'js_certificate_until']);
        $table->addColumn('created_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'created_at']);
        $table->addColumn('modified_at', 'datetime', ['null' => true, 'after' => 'created_by']);
        $table->addColumn('modified_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'modified_at']);
        $table->addColumn('archived_at', 'datetime', ['null' => true, 'after' => 'modified_by']);
        $table->addColumn('archived_by', 'integer', ['null' => true, 'limit' => MysqlAdapter::INT_REGULAR, 'precision' => 10, 'after' => 'archived_at']);
        $table->save();
        $table = $this->table("user");
        $table->removeIndexByName("fk_user_department1_idx");
        $table = $this->table("user");
        $table->addIndex(['department_hash'], ['name' => "fk_user_department1_idx", 'unique' => false])->save();
        $table = $this->table("user");
        $table->removeIndexByName("fk_user_position1_idx");
        $table = $this->table("user");
        $table->addIndex(['position_hash'], ['name' => "fk_user_position1_idx", 'unique' => false])->save();
        $table = $this->table("user");
        $table->removeIndexByName("fk_user_language1_idx");
        $table = $this->table("user");
        $table->addIndex(['language_hash'], ['name' => "fk_user_language1_idx", 'unique' => false])->save();
        $table = $this->table("user");
        $table->removeIndexByName("fk_user_gender1_idx");
        $table = $this->table("user");
        $table->addIndex(['gender_hash'], ['name' => "fk_user_gender1_idx", 'unique' => false])->save();
        $table = $this->table("user");
        $table->removeIndexByName("fk_user_city1_idx");
        $table = $this->table("user");
        $table->addIndex(['city_id'], ['name' => "fk_user_city1_idx", 'unique' => false])->save();
        $table = $this->table("user");
        $table->removeIndexByName("fk_app_user_permission1_idx");
        $table = $this->table("user");
        $table->addIndex(['permission_hash'], ['name' => "fk_app_user_permission1_idx", 'unique' => false])->save();
    }
}
